[project]
name = "airports-data-analysis"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "loguru>=0.7.3",
    "polars>=1.32.3",
    "pydrive2>=1.21.3",
    "python-dotenv>=1.1.1",
]
